In [1]:
import numpy as np

In [2]:
arr = np.arange(1_000_000)

In [3]:
lst = list(range(1_000_000))

In [4]:
%timeit arr2 = arr * 2

2.19 ms ± 78.2 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [5]:
%timeit lst2 = [x * 2 for x in lst]

104 ms ± 13.3 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


# The NumPy ndarray: A Multidimensional Array Object

In [6]:
data = np.array([[1.5, -0.1, 3],
                 [0, -3, 6.5]])


In [7]:
data

array([[ 1.5, -0.1,  3. ],
       [ 0. , -3. ,  6.5]])

In [8]:
data + data

array([[ 3. , -0.2,  6. ],
       [ 0. , -6. , 13. ]])

In [9]:
data * 10

array([[ 15.,  -1.,  30.],
       [  0., -30.,  65.]])

In [10]:
type(data)

numpy.ndarray

In [11]:
help(np.ndarray)

Help on class ndarray in module numpy:

class ndarray(builtins.object)
 |  ndarray(shape, dtype=float, buffer=None, offset=0,
 |          strides=None, order=None)
 |  
 |  An array object represents a multidimensional, homogeneous array
 |  of fixed-size items.  An associated data-type object describes the
 |  format of each element in the array (its byte-order, how many bytes it
 |  occupies in memory, whether it is an integer, a floating point number,
 |  or something else, etc.)
 |  
 |  Arrays should be constructed using `array`, `zeros` or `empty` (refer
 |  to the See Also section below).  The parameters given here refer to
 |  a low-level method (`ndarray(...)`) for instantiating an array.
 |  
 |  For more information, refer to the `numpy` module and examine the
 |  methods and attributes of an array.
 |  
 |  Parameters
 |  ----------
 |  (for the __new__ method; see Notes below)
 |  
 |  shape : tuple of ints
 |      Shape of created array.
 |  dtype : data-type, optional
 |

## Basic Attributes of the ndarray Class

In [12]:
# A tuple that contains the number of elements (i.e., the length) for each dimension (axis) of the array
data.shape

(2, 3)

In [13]:
# The data type of the elements in the array
data.dtype

dtype('float64')

In [14]:
# Number of dimensions (axes)
data.ndim

2

In [15]:
# The total numbers of elements in the array
data.size

6

In [16]:
# Number of bytes used to store the data
data.nbytes

48

## Creating ndarrays

### Arrays Created from Lists

In [17]:
data = np.array([1, 2, 3, 4])

In [18]:
data

array([1, 2, 3, 4])

In [19]:
data.ndim, data.shape

(1, (4,))

In [20]:
data = np.array([[1, 2], [3, 4]])

In [21]:
data

array([[1, 2],
       [3, 4]])

In [22]:
data.ndim, data.shape

(2, (2, 2))

### Arrays Filled with Constant Values

In [23]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [24]:
np.zeros((2, 3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [25]:
0 * np.empty((2, 3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [26]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [27]:
5.4 * np.ones(10)

array([5.4, 5.4, 5.4, 5.4, 5.4, 5.4, 5.4, 5.4, 5.4, 5.4])

In [28]:
np.full(10, 5.4)

array([5.4, 5.4, 5.4, 5.4, 5.4, 5.4, 5.4, 5.4, 5.4, 5.4])

In [29]:
# Creating Uninitialized Arrays
x = np.empty(10)
x.fill(5.4)

x

array([5.4, 5.4, 5.4, 5.4, 5.4, 5.4, 5.4, 5.4, 5.4, 5.4])

### Arrays Filled with Incremental Sequences

In [30]:
np.arange(0.0, 10, 1)

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [31]:
np.linspace(0, 9, 10)

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

### Arrays Filled with Logarithmic Sequences

In [32]:
# 5 data points between 10**0=1 to 10**2=100
np.logspace(0, 2, 5)

array([  1.        ,   3.16227766,  10.        ,  31.6227766 ,
       100.        ])

### Meshgrid Arrays

In [33]:
x = np.array([-1, 0, 1])

In [34]:
y = np.array([-2, 
              0, 
              2])

In [35]:
X, Y = np.meshgrid(x, y)

In [36]:
X, Y

(array([[-1,  0,  1],
        [-1,  0,  1],
        [-1,  0,  1]]),
 array([[-2, -2, -2],
        [ 0,  0,  0],
        [ 2,  2,  2]]))

In [37]:
Z = (X + Y) ** 2
Z

array([[9, 4, 1],
       [1, 0, 1],
       [1, 4, 9]])

In [38]:
np.mgrid[0:4, 0:4]

array([[[0, 0, 0, 0],
        [1, 1, 1, 1],
        [2, 2, 2, 2],
        [3, 3, 3, 3]],

       [[0, 1, 2, 3],
        [0, 1, 2, 3],
        [0, 1, 2, 3],
        [0, 1, 2, 3]]])

In [39]:
np.ogrid[0:11, 0:6]

[array([[ 0],
        [ 1],
        [ 2],
        [ 3],
        [ 4],
        [ 5],
        [ 6],
        [ 7],
        [ 8],
        [ 9],
        [10]]),
 array([[0, 1, 2, 3, 4, 5]])]

### Creating Arrays with Properties of Other Arrays

In [40]:
def f(x):
    # array of the same size and data type as x, and filled with ones
    y = np.ones_like(x)
    return y


### Creating Matrix Arrays

In [41]:
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [42]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [43]:
np.eye(4, k=1)

array([[0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.]])

In [44]:
np.eye(4, k=-1)

array([[0., 0., 0., 0.],
       [1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

In [45]:
np.diag(np.arange(0, 20, 5))

array([[ 0,  0,  0,  0],
       [ 0,  5,  0,  0],
       [ 0,  0, 10,  0],
       [ 0,  0,  0, 15]])

# Data Types

In [46]:
np.array([1, 2, 3], dtype=int).dtype

dtype('int32')

In [47]:
np.array([1, 2, 3], dtype=np.int32).dtype

dtype('int32')

In [48]:
np.array([1, 2, 3], dtype=np.int64).dtype

dtype('int64')

In [49]:
np.array([1, 2, 3], dtype=float).dtype

dtype('float64')

In [50]:
np.array([1, 2, 3], dtype=complex).dtype

dtype('complex128')

Once a NumPy array is created, its dtype cannot be changed, other than by creating
a new copy with type-casted array values. 

In [51]:
data = np.array([1, 2, 3], dtype=float)
data

array([1., 2., 3.])

In [52]:
data = np.array(data, dtype=int)
data

array([1, 2, 3])

In [53]:
data.astype(float)

array([1., 2., 3.])

Data Type Promotion

In [54]:
d1 = np.array([1, 2, 3], dtype=float)
d2 = np.array([1, 2, 3], dtype=complex)

d = d1 + d2
d

array([2.+0.j, 4.+0.j, 6.+0.j])

In [55]:
np.sqrt(np.array([-1, 0, 1]), dtype=complex)

array([0.+1.j, 0.+0.j, 1.+0.j])

Real and Imaginary Parts

In [56]:
data = np.array([1, 2, 3], dtype=complex)
data

array([1.+0.j, 2.+0.j, 3.+0.j])

In [57]:
data.real

array([1., 2., 3.])

In [58]:
data.real

array([1., 2., 3.])

In [59]:
help(np.real)

Help on function real in module numpy:

real(val)
    Return the real part of the complex argument.
    
    Parameters
    ----------
    val : array_like
        Input array.
    
    Returns
    -------
    out : ndarray or scalar
        The real component of the complex argument. If `val` is real, the type
        of `val` is used for the output.  If `val` has complex elements, the
        returned type is float.
    
    See Also
    --------
    real_if_close, imag, angle
    
    Examples
    --------
    >>> a = np.array([1+2j, 3+4j, 5+6j])
    >>> a.real
    array([1.,  3.,  5.])
    >>> a.real = 9
    >>> a
    array([9.+2.j,  9.+4.j,  9.+6.j])
    >>> a.real = np.array([9, 8, 7])
    >>> a
    array([9.+2.j,  8.+4.j,  7.+6.j])
    >>> np.real(1 + 1j)
    1.0



Explicit casting

In [60]:
int_array = np.arange(10)
calibers = np.array([.22, .270, .357, .380, .44, .50], dtype=np.float64)

In [61]:
int_array.astype(calibers.dtype)

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

## Order of Array Data in Memory

In [62]:
# C order
data = np.array([
  [1, 2, 3], 
  [4, 5, 6]], order="C", dtype=np.int32)

data.nbytes, data.strides, data.itemsize

(24, (12, 4), 4)

In [63]:
# F order
data = np.array([
  [1, 2, 3], 
  [4, 5, 6]], order="F", dtype=np.int32)

data.nbytes, data.strides, data.itemsize

(24, (4, 8), 4)

# Loading data

In [64]:
import os
import inspect

In [65]:
if "__file__" not in locals():
  fx = inspect.getframeinfo(inspect.currentframe())[0]
else:
  fx = __file__

os_dir = os.path.dirname(os.path.abspath(fx))
os_dir

'C:\\Users\\USER\\AppData\\Local\\Temp\\ipykernel_8600'

In [66]:
lending_co_data_numeric_1 = np.loadtxt("data/Lending-Company-Numeric-Data.csv", delimiter=',')
lending_co_data_numeric_1

array([[ 2000.,    40.,   365.,  3121.,  4241., 13621.],
       [ 2000.,    40.,   365.,  3061.,  4171., 15041.],
       [ 1000.,    40.,   365.,  2160.,  3280., 15340.],
       ...,
       [ 2000.,    40.,   365.,  4201.,  5001., 16600.],
       [ 1000.,    40.,   365.,  2080.,  3320., 15600.],
       [ 2000.,    40.,   365.,  4601.,  4601., 16600.]])

In [67]:
lending_co_data_numeric_2 = np.genfromtxt("./data/Lending-Company-Numeric-Data.csv", delimiter = ',')
lending_co_data_numeric_2

array([[ 2000.,    40.,   365.,  3121.,  4241., 13621.],
       [ 2000.,    40.,   365.,  3061.,  4171., 15041.],
       [ 1000.,    40.,   365.,  2160.,  3280., 15340.],
       ...,
       [ 2000.,    40.,   365.,  4201.,  5001., 16600.],
       [ 1000.,    40.,   365.,  2080.,  3320., 15600.],
       [ 2000.,    40.,   365.,  4601.,  4601., 16600.]])

In [68]:
np.array_equal(lending_co_data_numeric_1, lending_co_data_numeric_2)

True

In [69]:
lending_co_data_numeric_NAN = np.genfromtxt("data/Lending-Company-Numeric-Data-NAN.csv", delimiter=';')
lending_co_data_numeric_NAN

array([[ 2000.,    40.,   365.,  3121.,  4241., 13621.],
       [ 2000.,    40.,   365.,  3061.,  4171., 15041.],
       [ 1000.,    40.,   365.,  2160.,  3280., 15340.],
       ...,
       [   nan,    40.,   365.,  4201.,  5001., 16600.],
       [ 1000.,    40.,   365.,  2080.,  3320., 15600.],
       [ 2000.,    40.,   365.,  4601.,  4601., 16600.]])

In [70]:
lending_co_data_numeric_NAN = np.loadtxt("data/Lending-Company-Numeric-Data-NAN.csv", 
                                         delimiter=';',
                                         dtype=np.str_)
lending_co_data_numeric_NAN

array([['2000', '40', '365', '3121', '4241', '13621'],
       ['2000', '40', '365', '3061', '4171', '15041'],
       ['1000', '40', '365', '2160', '3280', '15340'],
       ...,
       ['', '40', '365', '4201', '5001', '16600'],
       ['1000', '40', '365', '2080', '3320', '15600'],
       ['2000', '40', '365', '4601', '4601', '16600']], dtype='<U5')

### Partial Cleaning While Importing

In [71]:
lending_co_data_numeric_NAN = np.genfromtxt("data/Lending-Company-Numeric-Data-NAN.csv",
                                            delimiter=';',
                                            usecols=(5, 0, 1),
                                            skip_header=2,
                                            skip_footer=2)
lending_co_data_numeric_NAN


array([[15340.,  1000.,    40.],
       [15321.,  2000.,    40.],
       [13720.,  2000.,    50.],
       ...,
       [16600.,  2000.,    40.],
       [16600.,  2000.,    40.],
       [16600.,    nan,    40.]])

In [72]:
lending_co_data_5, lending_co_data_0, lending_co_data_1 = np.genfromtxt("data/Lending-Company-Numeric-Data-NAN.csv",
                                                                        delimiter=';',
                                                                        usecols=(5, 0, 1),
                                                                        skip_header=2,
                                                                        skip_footer=2,
                                                                        unpack=True)
print(lending_co_data_5)
print(lending_co_data_0)
print(lending_co_data_1)

# Unpacking allows us to split the output array into smaller 1-D arrays.

[15340. 15321. 13720. ... 16600. 16600. 16600.]
[1000. 2000. 2000. ... 2000. 2000.   nan]
[40. 40. 50. ... 40. 40. 40.]


# Random Generators

In [73]:
# from numpy.random import Generator as gen
# from numpy.random import PCG64 as pcg
# array_RG = gen(pcg(seed=365))

In [74]:
array_rng = np.random.default_rng(seed=365)
array_rng.normal(size=(5, 5))


array([[-0.13640899,  0.09414431, -0.06300442,  1.05391641, -0.6866818 ],
       [-0.50922173, -0.7999526 ,  0.73041825,  0.08825439, -2.1177576 ],
       [ 0.65526774, -0.48095012, -0.5519114 , -0.58578662, -0.98257896],
       [ 1.12378166, -1.30984316, -0.04703774,  0.955272  ,  0.26071745],
       [-0.20023668, -1.50172484, -1.4929163 ,  0.96535084,  1.18694633]])

In [75]:
array_rng.normal(size=(5, 5))

# The seed is fixed for a single itteration.

array([[-0.76065577,  1.48158358,  0.01200258, -0.06846959,  0.25301664],
       [-0.52640788,  0.79613109,  0.28203421,  1.80238008,  0.93932117],
       [-0.53693283, -0.26317689, -1.77723035,  1.14900013, -2.20733915],
       [ 1.54116775, -0.5124932 , -2.14564563,  1.98878673,  0.32208907],
       [-1.2651495 ,  3.2714633 ,  1.78650493, -0.20233675,  0.20427467]])

## Generating Integers, Probabilities and Random Choices

In [76]:
array_rng.integers(low=10, high=100, size=(5, 5))


array([[42, 63, 34, 12, 86],
       [86, 16, 92, 23, 84],
       [72, 78, 93, 15, 91],
       [41, 90, 21, 57, 39],
       [52, 22, 85, 29, 80]], dtype=int64)

In [77]:
array_rng.random(size=(5, 5))


array([[0.36904177, 0.53629827, 0.81589813, 0.07632435, 0.9389407 ],
       [0.48395624, 0.9295958 , 0.23011817, 0.64945578, 0.02243555],
       [0.97401848, 0.35091164, 0.07297074, 0.52586653, 0.01239245],
       [0.22309532, 0.89845526, 0.89214756, 0.54528016, 0.9196353 ],
       [0.2630934 , 0.94166123, 0.28297619, 0.7369772 , 0.70370802]])

In [78]:
array_rng.choice((1, 2, 3, 4, 5), p=[0.1, 0.1, 0.1, 0.1, 0.6], size=(5, 5))


array([[3, 5, 5, 1, 5],
       [5, 1, 4, 1, 5],
       [4, 1, 1, 5, 1],
       [5, 5, 1, 1, 4],
       [5, 1, 2, 2, 1]])

## Randomly permute a sequence

In [79]:
array_rng.permutation(10)

array([5, 1, 7, 0, 2, 9, 3, 8, 6, 4])

In [80]:
array_rng.permutation(np.arange(25).reshape((5, 5)))

array([[15, 16, 17, 18, 19],
       [ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [20, 21, 22, 23, 24]])

## Generating Arrays From Known Distributions

In [81]:
array_rng.uniform(-1, 0, 100)


array([-0.78401038, -0.32072734, -0.35642403, -0.61474999, -0.83127516,
       -0.9316907 , -0.66293128, -0.68137157, -0.02460505, -0.19362942,
       -0.06562259, -0.62310718, -0.29288007, -0.01197997, -0.97166471,
       -0.87484876, -0.20363348, -0.52072438, -0.32243473, -0.65053981,
       -0.07696351, -0.54571412, -0.45349394, -0.77032982, -0.86888782,
       -0.62288637, -0.5195325 , -0.04231486, -0.96844074, -0.37823481,
       -0.23803823, -0.34765199, -0.79789563, -0.93889717, -0.25954919,
       -0.39954408, -0.4796162 , -0.82544187, -0.79203551, -0.094764  ,
       -0.24351316, -0.65570548, -0.28067526, -0.87127848, -0.02595932,
       -0.94201413, -0.64076293, -0.76749773, -0.91437838, -0.57004367,
       -0.67718775, -0.2067714 , -0.53324508, -0.38185796, -0.38478403,
       -0.51970814, -0.82220951, -0.66922285, -0.45243418, -0.85351789,
       -0.89491873, -0.79206528, -0.70747092, -0.86319393, -0.86784066,
       -0.70888072, -0.34196507, -0.60267931, -0.78356211, -0.14

In [82]:
array_rng.chisquare(2, size=(5, 5))

array([[3.87593769, 2.00336896, 1.82983228, 0.90996811, 0.95092658],
       [2.71315656, 1.16523702, 1.64067587, 4.27680936, 2.2115453 ],
       [4.09998203, 1.10342477, 0.80884398, 1.01593171, 0.11908365],
       [1.11311083, 5.05011941, 5.519539  , 1.95350239, 1.03086594],
       [0.4126938 , 0.56770425, 4.8164828 , 0.99670269, 1.38047788]])

In [83]:
array_rng.standard_normal((5, 5))

array([[-0.10686474,  0.61749937,  0.26997446,  1.08350131,  0.07161532],
       [-0.78057159,  0.07169797,  0.81496169,  1.7037499 , -0.0863218 ],
       [-0.15679723, -0.77076974, -1.3900946 ,  0.7202741 , -0.46203865],
       [-1.78142635,  0.79594281, -0.155089  , -0.50493422, -1.06318589],
       [-1.47929318, -0.05460508,  0.98014965, -0.2964393 , -0.6469837 ]])

In [84]:
array_rng.poisson(lam=10, size=(5, 5))


array([[10,  9,  9, 11, 10],
       [ 9, 10,  8, 10, 14],
       [10, 10, 14,  7, 12],
       [14, 13, 10, 14, 17],
       [11, 13,  9, 12, 13]], dtype=int64)

In [85]:
array_rng.binomial(n=100, p=0.4, size=(5, 5))


array([[35, 35, 45, 31, 30],
       [36, 41, 44, 36, 51],
       [40, 35, 35, 42, 36],
       [38, 33, 36, 35, 36],
       [35, 43, 44, 35, 43]], dtype=int64)

In [86]:
array_rng.gamma(2, 2, 100)

array([3.43473271, 7.94536298, 1.28315966, 4.68679329, 3.21272535,
       5.025894  , 2.1327471 , 1.2633906 , 4.50826636, 4.97304613,
       5.4734814 , 3.89624358, 6.22679714, 4.93852348, 5.62361114,
       1.19624548, 4.53747481, 1.85478133, 4.93459595, 3.50677306,
       3.08907859, 1.39610327, 8.29730431, 7.41518476, 0.98041066,
       8.51481672, 2.90052172, 4.40079102, 1.21759615, 1.42710261,
       4.16833754, 1.37433703, 2.16873547, 4.69978746, 0.98718597,
       4.55729956, 0.65106066, 5.84587338, 6.73974707, 4.85262774,
       4.02667947, 6.59828205, 1.22806616, 5.41983086, 4.04442266,
       2.5458625 , 4.8880371 , 3.18012075, 2.6377655 , 6.20518026,
       6.13470992, 2.77837479, 2.85839117, 4.04170949, 6.23633347,
       1.23887314, 3.10410743, 1.132077  , 0.7025339 , 3.98308213,
       6.06619449, 9.33209962, 2.45655848, 6.91250912, 4.48164305,
       3.98142745, 4.98825472, 9.57228503, 7.68984465, 7.29373154,
       4.83900752, 0.85816956, 5.56980856, 1.88239265, 4.53856

In [87]:
array_rng.logistic(loc=9, scale=1.2, size=(5, 5))


array([[ 8.85888262,  8.65496956,  3.45269609, 10.71197541, 10.62948247],
       [ 7.0500269 ,  9.72062774, 10.36730901,  7.84735088,  7.4478939 ],
       [ 9.08623652,  6.20594882,  9.04921692,  4.66741588,  9.04786039],
       [ 8.4143105 ,  9.67680208,  8.4655149 ,  8.16469102, 10.81036255],
       [11.28505576,  8.86536714,  8.65127335,  4.36926305,  6.91073563]])

# Index and slicing

## One-dimensional arrays

In [88]:
a = np.arange(0, 11)


In [89]:
a


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [90]:
a[0]  # the first element


0

In [91]:
a[-1] # the last element


10

In [92]:
a[4]  # the fifth element, at index 4


4

a[m:n] selects elements starting with m and ending with n − 1 :
m is inclusive and
n is exclusive

In [93]:
a[1:-1]


array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [94]:
a[1:-1:2]


array([1, 3, 5, 7, 9])

In [95]:
a[:5]


array([0, 1, 2, 3, 4])

In [96]:
a[-5:]


array([ 6,  7,  8,  9, 10])

In [97]:
a[::-1]


array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1,  0])

In [98]:
a[:] # select all elements in the given axis


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

## Multidimensional arrays

In [99]:
f = lambda m, n: n + 10 * m
A = np.fromfunction(f, (6, 6), dtype=np.int_)


In [100]:
A

array([[ 0,  1,  2,  3,  4,  5],
       [10, 11, 12, 13, 14, 15],
       [20, 21, 22, 23, 24, 25],
       [30, 31, 32, 33, 34, 35],
       [40, 41, 42, 43, 44, 45],
       [50, 51, 52, 53, 54, 55]])

In [101]:
A[:, 1]  # the second column


array([ 1, 11, 21, 31, 41, 51])

In [102]:
A[1, :]  # the second row


array([10, 11, 12, 13, 14, 15])

In [103]:
A[:3, :3]  # upper half diagonal block matrix


array([[ 0,  1,  2],
       [10, 11, 12],
       [20, 21, 22]])

In [104]:
A[3:, :3]  # lower left off-diagonal block matrix


array([[30, 31, 32],
       [40, 41, 42],
       [50, 51, 52]])

In [105]:
A[::2, ::2]  # every second element starting from 0, 0


array([[ 0,  2,  4],
       [20, 22, 24],
       [40, 42, 44]])

In [106]:
A[1::2, 1::3]  # every second element starting from 1, 1


array([[11, 14],
       [31, 34],
       [51, 54]])

## Views

In [107]:
# they are arrays that refer to the same data in the memory as the original array, 
# but with a different strides configuration

In [108]:
B = A[1:5, 1:5]

In [109]:
B

array([[11, 12, 13, 14],
       [21, 22, 23, 24],
       [31, 32, 33, 34],
       [41, 42, 43, 44]])

In [110]:
B[2]

array([31, 32, 33, 34])

In [111]:
B[2][0]

31

In [112]:
B[:, :] = 0

In [113]:
A

array([[ 0,  1,  2,  3,  4,  5],
       [10,  0,  0,  0,  0, 15],
       [20,  0,  0,  0,  0, 25],
       [30,  0,  0,  0,  0, 35],
       [40,  0,  0,  0,  0, 45],
       [50, 51, 52, 53, 54, 55]])

In [114]:
C = B[1:3, 1:3].copy()

In [115]:
C

array([[0, 0],
       [0, 0]])

In [116]:
C[:, :] = 1 

In [117]:
C

array([[1, 1],
       [1, 1]])

In [118]:
B

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

## Boolean indexing

In [119]:
names = np.array(["Bob", "Joe", "Will", "Bob", "Will", "Joe", "Joe"])


In [120]:
names


array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'], dtype='<U4')

In [121]:
data = np.array([[4, 7], [0, 2], [-5, 6], [0, 0], [1, 2], [-12, -4], [3, 4]])


In [122]:
data

array([[  4,   7],
       [  0,   2],
       [ -5,   6],
       [  0,   0],
       [  1,   2],
       [-12,  -4],
       [  3,   4]])

In [123]:
names == "Bob"

array([ True, False, False,  True, False, False, False])

In [124]:
data[names == "Bob"]

array([[4, 7],
       [0, 0]])

In [125]:
data[names == "Bob", 1]

array([7, 0])

In [126]:
data[names == "Bob", 1:]

array([[7],
       [0]])

In [127]:
names != "Bob"

array([False,  True,  True, False,  True,  True,  True])

In [128]:
~(names == "Bob")

array([False,  True,  True, False,  True,  True,  True])

In [129]:
mask = (names == "Bob") | (names == "Will")


In [130]:
mask


array([ True, False,  True,  True,  True, False, False])

In [131]:
data[mask]

array([[ 4,  7],
       [-5,  6],
       [ 0,  0],
       [ 1,  2]])

In [132]:
data[data < 0] = 0

In [133]:
data


array([[4, 7],
       [0, 2],
       [0, 6],
       [0, 0],
       [1, 2],
       [0, 0],
       [3, 4]])

In [134]:
data[names != "Joe"] = 7

In [135]:
data

array([[7, 7],
       [0, 2],
       [7, 7],
       [7, 7],
       [7, 7],
       [0, 0],
       [3, 4]])

## Fancy indexing

In [136]:
arr = np.fromfunction(lambda m, n: m, (8, 4))

In [137]:
arr

array([[0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.]])

In [138]:
# with python list
arr[[4, 3, 0, 6]]


array([[4., 4., 4., 4.],
       [3., 3., 3., 3.],
       [0., 0., 0., 0.],
       [6., 6., 6., 6.]])

In [139]:
# with numpy array
arr[np.array([4, 3, 0, 6])]


array([[4., 4., 4., 4.],
       [3., 3., 3., 3.],
       [0., 0., 0., 0.],
       [6., 6., 6., 6.]])

In [140]:
arr[[-3, -5, -7]]

array([[5., 5., 5., 5.],
       [3., 3., 3., 3.],
       [1., 1., 1., 1.]])

In [141]:
arr = np.arange(32).reshape((8, 4))
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [142]:
arr[[1, 5, 7, 2], [0, 3, 1, 2]]

array([ 4, 23, 29, 10])

In [143]:
arr[[1, 5, 7, 2]][:, [0, 3, 1, 2]]

array([[ 4,  7,  5,  6],
       [20, 23, 21, 22],
       [28, 31, 29, 30],
       [ 8, 11,  9, 10]])

<img src="images/numpy-indexing.png" />

# Reshaping and resizing

In [144]:
data = np.array([[1, 2], [3, 4]])

In [145]:
data

array([[1, 2],
       [3, 4]])

In [146]:
np.reshape(data, (1, 4))

array([[1, 2, 3, 4]])

In [147]:
data.reshape(4)

array([1, 2, 3, 4])

In [148]:
data.flatten()

array([1, 2, 3, 4])

In [149]:
data = np.arange(0, 5)
data

array([0, 1, 2, 3, 4])

In [150]:
column = data[:, np.newaxis]
column


array([[0],
       [1],
       [2],
       [3],
       [4]])

In [151]:
row = data[np.newaxis, :]
row


array([[0, 1, 2, 3, 4]])

In [152]:
np.vstack((data, data, data))

array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]])

In [153]:
np.hstack((data, data, data))

array([0, 1, 2, 3, 4, 0, 1, 2, 3, 4, 0, 1, 2, 3, 4])

In [154]:
data = data[:, np.newaxis]

In [155]:
np.hstack((data, data, data))

array([[0, 0, 0],
       [1, 1, 1],
       [2, 2, 2],
       [3, 3, 3],
       [4, 4, 4]])

# Vectorized expressions

## Arithmetic operations

In [156]:
x = np.array([[1, 2],
              [3, 4]])

y = np.array([[5, 6],
              [7, 8]])


In [157]:
# Hadamard product
x * y

array([[ 5, 12],
       [21, 32]])

In [158]:
np.multiply(x, y)

array([[ 5, 12],
       [21, 32]])

In [159]:
x.T

array([[1, 3],
       [2, 4]])

In [160]:
x.swapaxes(0, 1)

array([[1, 3],
       [2, 4]])

In [161]:
np.dot(x.T, x)

array([[10, 14],
       [14, 20]])

In [162]:
x.T @ x

array([[10, 14],
       [14, 20]])

## Universal Functions

In [163]:
x = np.linspace(-1, 1, 11)
x

array([-1. , -0.8, -0.6, -0.4, -0.2,  0. ,  0.2,  0.4,  0.6,  0.8,  1. ])

In [164]:
y = np.sin(np.pi * x)
y

array([-1.22464680e-16, -5.87785252e-01, -9.51056516e-01, -9.51056516e-01,
       -5.87785252e-01,  0.00000000e+00,  5.87785252e-01,  9.51056516e-01,
        9.51056516e-01,  5.87785252e-01,  1.22464680e-16])

In [165]:
np.round(y, decimals=4)

array([-0.    , -0.5878, -0.9511, -0.9511, -0.5878,  0.    ,  0.5878,
        0.9511,  0.9511,  0.5878,  0.    ])

In [166]:
np.sin(x) ** 2 + np.cos(x) ** 2

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [167]:
np.add(np.sin(x) ** 2, np.cos(x) ** 2)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [168]:
arr = array_rng.standard_normal(7) * 5
arr

array([  5.53046427,  -0.06408775,   8.04208444,  -7.56497922,
         0.92869901, -13.47078752,   1.49207767])

In [169]:
remainder, whole_part = np.modf(arr)

In [170]:
remainder


array([ 0.53046427, -0.06408775,  0.04208444, -0.56497922,  0.92869901,
       -0.47078752,  0.49207767])

In [171]:
whole_part


array([  5.,  -0.,   8.,  -7.,   0., -13.,   1.])

In [172]:
out = np.zeros_like(arr)
np.add(arr, 1, out=out)

array([  6.53046427,   0.93591225,   9.04208444,  -6.56497922,
         1.92869901, -12.47078752,   2.49207767])

In [173]:
out

array([  6.53046427,   0.93591225,   9.04208444,  -6.56497922,
         1.92869901, -12.47078752,   2.49207767])

In [174]:
def heaviside(x):
    return 1 if x > 0 else 0

In [175]:
x = np.linspace(-5, 5, 11)

In [176]:
# slow since the original function must be called for each element in the array
heaviside = np.vectorize(heaviside)

In [177]:
heaviside(x)

array([0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1])

In [178]:
def heaviside(x):
    return 1.0 * (x > 0)

In [179]:
heaviside(x)

array([0., 0., 0., 0., 0., 0., 1., 1., 1., 1., 1.])

## Aggregate functions

In [180]:
data = np.random.normal(size=(15, 15))

In [181]:
data

array([[-1.2750039 , -1.92817143, -1.29488905,  0.10633005,  0.92259054,
        -0.82103556,  0.73050036, -1.37188183, -0.79815186,  0.90954106,
        -1.91115357, -0.06888929,  0.39708772,  0.41840691,  0.67557472],
       [-0.98354887,  0.9991649 ,  0.42954947,  1.00010188,  0.25781785,
        -2.18844274, -0.70523561, -1.63344333,  0.36564463,  0.4254809 ,
         1.38754214,  0.91794404, -0.4989188 ,  0.88608608,  0.94864783],
       [ 0.1179682 ,  1.48829063,  1.01871421, -1.57059537,  0.881713  ,
         2.49772933,  1.28074773, -1.80571612,  0.23662143, -0.31382559,
         1.03075833,  0.02143768,  0.09179106, -0.22068485, -0.02743868],
       [-0.15064548, -0.51876767, -0.77431092,  0.96698277, -0.00780816,
        -0.28838949,  0.53751461, -0.03298381, -0.02994484, -1.17367144,
        -0.80537085, -0.46373264, -1.61007923,  0.01004279,  1.38764704],
       [-0.75463965,  0.32286468,  0.42819873, -0.79932361,  0.66397192,
         1.77374762,  0.54670576, -0.61553116, 

In [182]:
np.mean(data)

0.02662048245905867

In [183]:
data.mean()

0.02662048245905867

In [184]:
data.mean(axis=1)

array([-0.35394301,  0.10722603,  0.3151674 , -0.19690116, -0.19273594,
        0.03780404, -0.20334063, -0.30111152,  0.40776395,  0.61266763,
       -0.37769135, -0.02440647,  0.17661993, -0.0798743 ,  0.47206265])

In [185]:
np.arange(101).cumsum()

array([   0,    1,    3,    6,   10,   15,   21,   28,   36,   45,   55,
         66,   78,   91,  105,  120,  136,  153,  171,  190,  210,  231,
        253,  276,  300,  325,  351,  378,  406,  435,  465,  496,  528,
        561,  595,  630,  666,  703,  741,  780,  820,  861,  903,  946,
        990, 1035, 1081, 1128, 1176, 1225, 1275, 1326, 1378, 1431, 1485,
       1540, 1596, 1653, 1711, 1770, 1830, 1891, 1953, 2016, 2080, 2145,
       2211, 2278, 2346, 2415, 2485, 2556, 2628, 2701, 2775, 2850, 2926,
       3003, 3081, 3160, 3240, 3321, 3403, 3486, 3570, 3655, 3741, 3828,
       3916, 4005, 4095, 4186, 4278, 4371, 4465, 4560, 4656, 4753, 4851,
       4950, 5050])

In [186]:
arr = np.array([[0, 1, 2],
                [3, 4, 5],
                [6, 7, 8]])


In [187]:
arr.cumsum(axis=0)

array([[ 0,  1,  2],
       [ 3,  5,  7],
       [ 9, 12, 15]])

In [188]:
arr.cumsum(axis=1)

array([[ 0,  1,  3],
       [ 3,  7, 12],
       [ 6, 13, 21]])

In [189]:
data = np.random.normal(size=(5, 10, 15))

In [190]:
data

array([[[ 3.89276965e-01,  6.04682176e-01, -8.19428813e-01,
         -1.04029864e+00,  9.48913025e-01,  7.33470944e-01,
          1.10108315e+00, -4.11354026e-01, -1.36247794e+00,
         -7.29603403e-01,  3.14562660e-02,  6.05071091e-01,
          8.60862549e-01,  2.31229495e-01,  1.09395318e+00],
        [ 1.80797912e-01, -1.54728128e+00, -6.94156878e-01,
         -8.06912566e-02, -1.78121923e+00, -1.82530509e+00,
         -2.68329060e-01, -9.89065853e-01,  1.91881126e+00,
          5.62553761e-01,  2.19696996e-01,  7.73756384e-01,
         -1.18214219e+00,  1.84452569e-01, -1.28052604e-01],
        [ 9.65263897e-01,  3.04484310e-01,  3.12064889e-01,
         -1.18811576e+00, -5.55374007e-01, -1.14094791e+00,
          4.59587681e-01,  8.61694487e-01,  9.87650318e-01,
          1.26831312e+00,  5.09973800e-01,  1.53621711e+00,
          4.46615992e-01,  1.96062569e+00,  5.47691630e-01],
        [-8.74139924e-01, -1.01994525e+00,  1.37619222e+00,
         -2.70972262e-01, -1.09229221

In [191]:
data.sum(axis=0)

array([[-0.33194429,  1.70466191, -1.04968478, -1.80616911, -2.94689426,
        -0.89857816,  2.38236809, -4.20432612, -1.19299627, -0.77970378,
         2.13746159,  0.34844938,  1.48107734,  1.02842603,  0.04003044],
       [ 0.67867915, -0.33075799,  0.02924921,  0.09553585,  0.11878524,
        -4.21811791, -0.83858986, -0.27163506,  1.4662224 ,  1.42071288,
         1.95157572,  1.2850587 , -1.32316209,  0.05641337, -0.45268022],
       [-2.23688673,  0.29672936,  2.50247657, -5.39847713, -1.89701236,
        -2.39710913,  3.08445639,  2.50283866, -4.35651981,  0.35388671,
        -1.27635739, -2.92931575,  2.01561296,  0.76626515,  1.46207326],
       [-3.12057937, -0.51698453,  3.82413778,  1.67193254, -0.98283392,
        -1.7559748 ,  1.41213747, -1.53664664,  0.18864411,  2.34573223,
        -1.74593417, -1.0240145 ,  3.16058427,  3.15846518, -0.945665  ],
       [ 0.93740527, -0.64107702,  3.66719949, -0.41374628,  1.47847753,
         0.7440067 , -0.85680112, -0.93982913, 

In [192]:
data.sum(axis=0).shape

(10, 15)

In [193]:
data.sum(axis=(0, 2)).shape

(10,)

<img src="images/numpy-sum.png" />

In [194]:
a = np.arange(30).reshape(2, 3, 5)

In [195]:
a

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14]],

       [[15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29]]])

In [196]:
#           p  p  p  p  p
#           o  o  o  o  o
#           s  s  s  s  s

#    dim 2  0  1  2  3  4

#           |  |  |  |  |
# dim 0     ↓  ↓  ↓  ↓  ↓
# ----> [[[ 0  1  2  3  4]   <---- dim 1, pos 0
# pos 0   [ 5  6  7  8  9]   <---- dim 1, pos 1
#         [10 11 12 13 14]]  <---- dim 1, pos 2
# dim 0
# ---->  [[15 16 17 18 19]   <---- dim 1, pos 0
# pos 1   [20 21 22 23 24]   <---- dim 1, pos 1
#         [25 26 27 28 29]]] <---- dim 1, pos 2
#           ↑  ↑  ↑  ↑  ↑
#           |  |  |  |  |

#    dim 2  p  p  p  p  p
#           o  o  o  o  o
#           s  s  s  s  s

#           0  1  2  3  4


In [197]:
a[:, :, :]

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14]],

       [[15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29]]])

In [198]:
a[0, :, :]  # dim 0, pos 0

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [199]:
a[1, :, :] # dim 0, pos 1

array([[15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29]])

In [200]:
a[:, 1, :] # dim 1, pos 1

array([[ 5,  6,  7,  8,  9],
       [20, 21, 22, 23, 24]])

In [201]:
a[:, :, 3] # dim 2, pos 3

array([[ 3,  8, 13],
       [18, 23, 28]])

In [202]:
np.array_equal(a.sum(axis=0),
               a[0, :, :] +
               a[1, :, :])

True

In [203]:
np.array_equal(a.sum(axis=1),
               a[:, 0, :] +
               a[:, 1, :] +
               a[:, 2, :])


True

In [204]:
np.array_equal(a.sum(axis=2),
               a[:, :, 0] +
               a[:, :, 1] +
               a[:, :, 2] +
               a[:, :, 3] +
               a[:, :, 4])

True

## Set operations

In [205]:
a = np.unique([1, 2, 3, 3])

In [206]:
b = np.unique([2, 3, 4, 4, 5, 6, 5])

In [207]:
np.in1d(a, b)

array([False,  True,  True])

In [208]:
np.isin(a, b)

array([False,  True,  True])

In [209]:
1 in a

True

In [210]:
1 in b

False

In [211]:
np.all(np.isin(a, b))

False

In [212]:
np.union1d(a, b)

array([1, 2, 3, 4, 5, 6])

In [213]:
np.intersect1d(a, b)

array([2, 3])

In [214]:
np.setdiff1d(a, b)

array([1])

In [215]:
np.setdiff1d(b, a)

array([4, 5, 6])

# Conditional Expressions

In [216]:
arr = array_rng.standard_normal(100)

In [217]:
(arr > 0).sum()

49

In [218]:
(arr <= 0).sum()

51

In [219]:
a = np.array([1, 2, 3, 4])
b = np.array([4, 3, 2, 1])

In [220]:
a < b

array([ True,  True, False, False])

In [221]:
# All elements in a are smaller than their corresponding element in b
np.all(a < b)

False

In [222]:
# Some elements in a are smaller than their corresponding elemment in b
np.any(a < b)

True

In [223]:
x = np.array([-2, -1, 0, 1, 2])


In [224]:
x > 0

array([False, False, False,  True,  True])

In [225]:
1 * (x > 0)

array([0, 0, 0, 1, 1])

In [226]:
x * (x > 0)

array([0, 0, 0, 1, 2])

In [227]:
x = np.linspace(-5, 5, 11)

In [228]:
1 * np.logical_and(x >= -2, x <= 3)

array([0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0])

In [229]:
1 * (x >= -2) * (x <= 3)

array([0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0])

In [230]:
xarr = np.array([1.1, 1.2, 1.3, 1.4, 1.5])

In [231]:
yarr = np.array([2.1, 2.2, 2.3, 2.4, 2.5])

In [232]:
cond = np.array([True, False, True, True, False])

In [233]:
result = [x if c else y
          for x, y, c in zip(xarr, yarr, cond)]


In [234]:
result

[1.1, 2.2, 1.3, 1.4, 2.5]

In [235]:
result = np.where(cond, xarr, yarr)

In [236]:
result

array([1.1, 2.2, 1.3, 1.4, 2.5])

In [237]:
arr = array_rng.standard_normal((4, 4))

In [238]:
arr > 0

array([[ True,  True, False, False],
       [ True,  True, False, False],
       [False, False, False, False],
       [ True, False,  True, False]])

In [239]:
np.where(arr > 0, 2, -2)

array([[ 2,  2, -2, -2],
       [ 2,  2, -2, -2],
       [-2, -2, -2, -2],
       [ 2, -2,  2, -2]])

In [240]:
# set only positive values to 2
np.where(arr > 0, 2, arr)

array([[ 2.        ,  2.        , -1.22333277, -0.65844789],
       [ 2.        ,  2.        , -2.4513762 , -0.59170916],
       [-0.67162866, -0.90789899, -0.82704437, -0.95252452],
       [ 2.        , -1.1529053 ,  2.        , -0.38102972]])

In [241]:
x = np.linspace(-4, 4, 9)

In [242]:
x

array([-4., -3., -2., -1.,  0.,  1.,  2.,  3.,  4.])

In [243]:
np.where(x < 0, x**2, x**3)

array([16.,  9.,  4.,  1.,  0.,  1.,  8., 27., 64.])

In [244]:
np.select(condlist=[x < -1, x < 2, x >= 2],
          choicelist=[x**2, x**3, x**4])


array([ 16.,   9.,   4.,  -1.,   0.,   1.,  16.,  81., 256.])

In [245]:
np.choose([0, 0, 0, 1, 1, 1, 2, 2, 2],
          choices=[x**2, x**3, x**4])

array([ 16.,   9.,   4.,  -1.,   0.,   1.,  16.,  81., 256.])

In [246]:
np.take([x**2, x**3], [0, 3])

array([16.,  1.])

In [247]:
np.nonzero(abs(x) > 2)

(array([0, 1, 7, 8], dtype=int64),)

In [248]:
x[abs(x) > 2]

array([-4., -3.,  3.,  4.])

In [249]:
x[np.nonzero(abs(x) > 2)]

array([-4., -3.,  3.,  4.])

# Flipping data

In [250]:
data = np.arange(9).reshape(3, 3)

data

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [251]:
np.transpose(data)

array([[0, 3, 6],
       [1, 4, 7],
       [2, 5, 8]])

In [252]:
np.fliplr(data)

array([[2, 1, 0],
       [5, 4, 3],
       [8, 7, 6]])

In [253]:
np.flipud(data)

array([[6, 7, 8],
       [3, 4, 5],
       [0, 1, 2]])

In [254]:
np.rot90(data)

array([[2, 5, 8],
       [1, 4, 7],
       [0, 3, 6]])

## Matrix and vector operations

In [255]:
A = np.arange(1, 7).reshape(2, 3)

In [256]:
B = np.arange(1, 7).reshape(3, 2)

In [257]:
A, B

(array([[1, 2, 3],
        [4, 5, 6]]),
 array([[1, 2],
        [3, 4],
        [5, 6]]))

In [258]:
np.dot(A, B)

array([[22, 28],
       [49, 64]])

In [259]:
A @ B

array([[22, 28],
       [49, 64]])

In [260]:
np.matmul(A, B)

array([[22, 28],
       [49, 64]])

In [261]:
A.dot(B)

array([[22, 28],
       [49, 64]])

In [262]:
np.dot(B, A)

array([[ 9, 12, 15],
       [19, 26, 33],
       [29, 40, 51]])

In [263]:
A = np.random.rand(3, 3)
B = np.random.rand(3, 3)

In [264]:
A = np.matrix(A)

In [265]:
A

matrix([[0.87433045, 0.56879803, 0.00801333],
        [0.10033225, 0.35126977, 0.56852102],
        [0.85209763, 0.49452761, 0.81699878]])

In [266]:
B = np.matrix(B)

In [267]:
Ap = B * A * B.I

In [268]:
Ap

matrix([[ 1.30394382,  0.60949836, -0.73618279],
        [ 0.91192179,  1.72848129, -2.29380322],
        [ 0.43641   ,  0.84822525, -0.98982611]])

In [269]:
A = np.asmatrix(A)

In [270]:
B = np.asmatrix(B)

In [271]:
Ap = B * A * B.I

In [272]:
Ap = np.asarray(Ap)

In [273]:
Ap

array([[ 1.30394382,  0.60949836, -0.73618279],
       [ 0.91192179,  1.72848129, -2.29380322],
       [ 0.43641   ,  0.84822525, -0.98982611]])

In [274]:
x = np.arange(3)

In [275]:
np.inner(x, x)

5

In [276]:
np.dot(x, x)

5

In [277]:
y = x[:, np.newaxis]

In [278]:
y

array([[0],
       [1],
       [2]])

In [279]:
np.dot(y.T, y)

array([[5]])

In [280]:
x = np.array([1, 2, 3])

In [281]:
np.outer(x, x) 

array([[1, 2, 3],
       [2, 4, 6],
       [3, 6, 9]])

In [282]:
np.kron(x, x) 

array([1, 2, 3, 2, 4, 6, 3, 6, 9])

In [283]:
np.kron(x[:, np.newaxis], x[np.newaxis, :])

array([[1, 2, 3],
       [2, 4, 6],
       [3, 6, 9]])

In [284]:
np.kron(np.ones((2,2)), np.identity(2))

array([[1., 0., 1., 0.],
       [0., 1., 0., 1.],
       [1., 0., 1., 0.],
       [0., 1., 0., 1.]])

In [285]:
np.kron(np.identity(2), np.ones((2,2)))

array([[1., 1., 0., 0.],
       [1., 1., 0., 0.],
       [0., 0., 1., 1.],
       [0., 0., 1., 1.]])

In [286]:
x = np.array([1, 2, 3, 4])
y = np.array([5, 6, 7, 8])

In [287]:
np.einsum("mk,kn", A, B)

array([[1.02329808, 0.74025363, 1.0434778 ],
       [0.33425768, 0.15098717, 0.72651054],
       [1.08946071, 0.75688655, 1.42406875]])

In [288]:
np.alltrue(np.einsum("mk,kn", A, B) == np.dot(A, B))

False

In [305]:
X = array_rng.standard_normal((5, 5))

In [306]:
mat = X.T @ X

In [307]:
from numpy.linalg import inv, qr
inv(mat)

array([[ 0.84109623,  0.55041141, -0.13134876, -0.07924755, -0.63574725],
       [ 0.55041141,  1.49506376, -1.35074708,  0.36921756, -0.40968924],
       [-0.13134876, -1.35074708,  1.8552861 , -0.50585965,  0.09548444],
       [-0.07924755,  0.36921756, -0.50585965,  0.31035271,  0.24491476],
       [-0.63574725, -0.40968924,  0.09548444,  0.24491476,  0.92195803]])

In [308]:
mat @ inv(mat)

array([[ 1.00000000e+00, -1.02038067e-16, -4.63635215e-18,
        -2.58151607e-17, -1.67603122e-16],
       [ 1.14810697e-17,  1.00000000e+00, -7.29456153e-16,
         3.84917316e-16,  4.52945948e-16],
       [ 1.43906302e-16, -3.53442593e-16,  1.00000000e+00,
        -3.74555198e-16, -1.56887300e-16],
       [-6.80779970e-16, -9.52321148e-16, -7.50346257e-16,
         1.00000000e+00,  7.41859461e-16],
       [-4.35113134e-16, -2.44227671e-16,  5.50588818e-17,
        -1.50840850e-16,  1.00000000e+00]])

# Sorting

In [289]:
arr = array_rng.standard_normal(6)
arr

array([-1.51783705,  0.24826992,  1.56819686, -0.93678328, -1.8376414 ,
       -1.09679365])

In [290]:
arr.sort()

In [291]:
arr

array([-1.8376414 , -1.51783705, -1.09679365, -0.93678328,  0.24826992,
        1.56819686])

In [292]:
arr = array_rng.standard_normal((5, 3))

In [293]:
arr.sort(axis=0)

In [294]:
arr

array([[-1.57746828, -0.98383509, -1.23201145],
       [-0.40018935, -0.49158597, -0.27026632],
       [-0.32932215,  0.16751287,  0.2306201 ],
       [-0.26290633,  0.9586145 ,  0.26274583],
       [ 1.19078083,  1.03354637,  0.39389702]])

In [295]:
arr.sort(axis=1)

In [296]:
arr

array([[-1.57746828, -1.23201145, -0.98383509],
       [-0.49158597, -0.40018935, -0.27026632],
       [-0.32932215,  0.16751287,  0.2306201 ],
       [-0.26290633,  0.26274583,  0.9586145 ],
       [ 0.39389702,  1.03354637,  1.19078083]])

# File Input and Output with Arrays

In [297]:
arr = np.arange(10)

In [298]:
# np.save("data/some_array", arr)

In [299]:
# np.load("data/some_array.npy")

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [300]:
# np.savez("data/array_archive.npz", a=arr, b=arr)

In [302]:
# arch = np.load("data/array_archive.npz")

In [303]:
# arch["b"]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [304]:
# np.savez_compressed("data/arrays_compressed.npz", a=arr, b=arr)